### PR TITLE
Add send function

### PR DESCRIPTION
**Pull request by Nugetzrul3**
Initial staging for adding the send function. Needs review.

### CODE REVIEW

**Comment by volbil** [comment]
Looking good to me 👍

**Review by volbil — APPROVED** [review]

**Comment by hardyanz** [comment]
i have balance 1300 sugar. i send to another wallet 1200 sugar + fee 1 sugar. Not enough funds? why? help me

**Comment by BANGUYA** [comment]
i have balance 1000 sugar, but i can't send 500 sugar + fee 1 sugar to another wallet ?? Not enough funds? why? help me

**Review by bitcoinworldhub — COMMENTED** [review]
js/send.js

**Comment by bitcoinworldhub** [comment]
https://guides.github.com/features/mastering-markdown/

**Comment by bitcoinworldhub** [comment]
mbc1q89xq7nc0vzyl077wxzk6zkuflu99csav0gjuku

**Pull request merged**
